# Workflow that runs unit tests at github
# for multiple versions of python. Runs on
# the latest ubuntu and macos. Uses uv.
# Triggered on both push and pull.
#
# Niles Oien November 2025.

name: uv pytest

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # The first job is for ubuntu.
  build-ubuntu:
    name: Test-ubuntu
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.12"
          - "3.13"
          - "3.14"

    steps:
      - uses: actions/checkout@v5 # Check out the repo

      - name: Install uv and set the Python version
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Init uv
        run: uv init --name FastAPI_example --description "An example of FastAPI" --bare .

      - name: Package install
        run: uv add -r requirements.in

      - name: Write trivial test database
        run: cd database/; ./uv_makeDB.sh; cd ../

      - name: MAIN TEST : Run pytest unit tests with uv in verbose mode
        run: uv run pytest -v

# Another job, same thing on macos
  build-mac:
    name: Test-mac
    runs-on: macos-latest
    strategy:
      matrix:
        python-version:
          - "3.12"
          - "3.13"
          - "3.14"

    steps:
      - uses: actions/checkout@v5 # Check out the repo

      - name: Install uv and set the Python version
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Init uv
        run: uv init --name FastAPI_example --description "An example of FastAPI" --bare .

      - name: Package install
        run: uv add -r requirements.in

      - name: Write trivial test database
        run: cd database/; ./uv_makeDB.sh; cd ../

      - name: MAIN TEST : Run pytest unit tests with uv in verbose mode
        run: uv run pytest -v

